FROM node:20 AS builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend . 

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN echo "Building with API URL: ${VITE_API_BASE_URL}"  

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]