version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile.local
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    env_file:
      - .env.local
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile.local
      args: 
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env.local

  db:
    image: postgres:15
    container_name: spearo-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local

  cache:
    image: redis:latest
    container_name: spearo-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:

# Note - need to pass in the .env.local file to the compose command `docker-compose --env-file .env.local up --build`