version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_NAME}
      - REDIS_URL=redis://cache:6379
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: spearo-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis:latest
    container_name: spearo-redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data: