version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://postgres:password@db:5432/spearo
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

#   db:
#     image: postgres:15
#     container_name: spearo-db
#     restart: always
#     environment:
#       POSTGRES_USER: benc
#       POSTGRES_PASSWORD: spearo
#       POSTGRES_DB: spearo
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: