apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:  
        - name: spearo-backend
          image: gcr.io/possible-tape-450509-e4/spearo-backend  
          ports:
            - containerPort: 5000  
          envFrom:
            - configMapRef:
                name: spearo-env
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000